openapi: 3.0.0
info:
  title: Video Surveillance API
  description: API documentation for viewing camera video streams
  version: 1.0.0
servers:
  - url: http://localhost:3000

paths:
  /cameras:
    get:
      summary: Get the list of cameras
      responses:
        '200':
          description: List of cameras
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    cameraId:
                      type: string
                    cameraName:
                      type: string
                    cameraLocation:
                      type: string
        '500':
          description: Error while retrieving the list of cameras

  /camera/{cameraId}/stream:
    get:
      summary: Get the video stream of a camera
      parameters:
        - name: cameraId
          in: path
          description: Camera ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Camera video stream
          content:
            video/mp4:
              schema:
                type: string
                format: binary
        '404':
          description: Camera not found